name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Generate Snake
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: PravalikaKadakanchi
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      - name: Push to output branch
        run: |
          git config --global user.name  "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add -f dist/
          git stash
          git fetch origin output 2>/dev/null || true
          git checkout --orphan output-new
          git rm -rf . 2>/dev/null || true
          git stash pop 2>/dev/null || true
          cp -r dist/* . 2>/dev/null || true
          git add github-contribution-grid-snake*.svg
          git commit -m "Update snake animation"
          git push origin HEAD:output --force
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
